name: Docker build and push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]


jobs:
  docker-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: book-hub-umsp/bh-infrastructure/.github/workflows/docker-publish.yml@master
    secrets: inherit
    
  deploy:
    needs: [docker-build]
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Extract tag
      id: get-tag
      run: |
        tag=$(echo ${{  github.ref_name }} | cut -dv -f2)
        echo "::set-output name=tag::$tag"
    - name: Job reload
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ vars.ENV_SSH_HOST }}
        username: ${{ secrets.ENV_SSH_USER }}
        password: ${{ secrets.ENV_SSH_PASSWORD }}
        script: |
          cd ${{ vars.ENV_APP_PATH }} &&
          nomad job run \
            -token ${{ secrets.ENV_NOMAD_TOKEN }} \
            -var-file ${{ vars.ENV_SECRET_FILE_PATH }} 
            -var main-api-version="${{ steps.get-tag.outputs.tag }}" \ 
            ${{ vars.ENV_JOB_FILE_PATH }}
