name: Create git tag

on:
  pull_request:
    types: [closed]


jobs:
  git-tag-create:
    permissions:
      contents: write
    uses: book-hub-umsp/bh-shared-actions/.github/workflows/version.yml@master
    secrets: inherit
