name: Docker build and push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  INFRO_REPO: book-hub-umsp/bh-infrastructure
  TARGET_BRANCH: master
  
jobs:
  docker-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: book-hub-umsp/bh-shared-actions/.github/workflows/docker-publish.yml@master
    secrets: inherit
    
  deploy:
    needs: [docker-build]
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Extract tag
      id: get-tag
      run: |
        tag=$(echo ${{  github.ref_name }} | cut -dv -f2)
        echo "::set-output name=tag::$tag"
    - name: Checkout Infro repo
      uses: actions/checkout@v4
      with:
        repository: '${{ env.INFRO_REPO }}'
        ref: '${{ env.TARGET_BRANCH }}'
        token: '${{ secrets.WORKFLOW_TOKEN }}'
    - name: Setup `nomad`
      uses: hashicorp/setup-nomad@main
      id: setup
      with:
        version: ${{ vars.ENV_NOMAD_VERSION }}
    - name: Plan job
      env:
        NOMAD_ADDR: ${{ vars.ENV_NOMAD_ADDR }}
      run: |
        nomad job plan \
          -token ${{ secrets.ENV_NOMAD_TOKEN }} \
          -var ROOT_PASS ${{ secrets.ENV_VAR_ROOT_PASS }} \
          -var main-api-version ${{ steps.get-tag.outputs.tag }} \
          ${{ vars.ENV_JOB_FILE_PATH }}
    - name: Run job
      env:
        NOMAD_ADDR: ${{ vars.ENV_NOMAD_ADDR }}
      run: |
        nomad job run \
          -token ${{ secrets.ENV_NOMAD_TOKEN }} \
          -var ROOT_PASS ${{ secrets.ENV_VAR_ROOT_PASS }} \
          -var main-api-version ${{ steps.get-tag.outputs.tag }} \ 
          ${{ vars.ENV_JOB_FILE_PATH }}
      
