name: Docker build and push

on:
  push:
    # branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]


env:
  INFRO_REPO: book-hub-umsp/bh-infrastructure
  TARGET_BRANCH: master
  
jobs:
  docker-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: book-hub-umsp/bh-shared-actions/.github/workflows/docker-publish.yml@master
    secrets: inherit    
