name: Deploy to Nomad cluster

on:
  push:
    # branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      service_version:
        description: 'Use version of service in format "{major}.{minor}.{patch}"'
        required: true
        type: string
        
env:
  INFRO_REPO: book-hub-umsp/bh-infrastructure
  INFRO_REPO_BRANCH: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Extract version from git tag
      if: github.event_name == 'push'
      id: get-tag
      run: |
        tag=$(echo ${{  github.ref_name }} | cut -dv -f2)
        echo "::set-output name=tag::$tag"
    - name: Checkout Infro repo
      uses: actions/checkout@v4
      with:
        repository: '${{ env.INFRO_REPO }}'
        ref: ${{ env.INFRO_REPO_BRANCH }}
        token: '${{ secrets.WORKFLOW_TOKEN }}'
    - name: Setup `nomad`
      uses: hashicorp/setup-nomad@main
      id: setup
      with:
        version: ${{ vars.ENV_NOMAD_VERSION }}
    - run: echo "${{ steps.get-tag.outputs.tag && steps.get-tag.outputs.tag || github.event.inputs.service_version }}"
    - name: Plan job
      continue-on-error: true # becase nomad job plan can return 1 as exit code on allocation creation
      env:
        NOMAD_ADDR: ${{ vars.ENV_NOMAD_ADDR }}
        SERVICE_VERSION: ${{ steps.get-tag.outputs.tag && steps.get-tag.outputs.tag || github.event.inputs.service_version }}
      run: |
        nomad job plan -token=${{ secrets.ENV_NOMAD_TOKEN }} -var ROOT_PASS=${{ secrets.ENV_VAR_ROOT_PASS }} -var main-api-version=${{ env.SERVICE_VERSION }} ${{ vars.ENV_JOB_PATH }}
    - name: Run job
      env:
        NOMAD_ADDR: ${{ vars.ENV_NOMAD_ADDR }}
        SERVICE_VERSION: ${{ steps.get-tag.outputs.tag && steps.get-tag.outputs.tag || github.event.inputs.service_version }}
      run: |
        nomad job run -token=${{ secrets.ENV_NOMAD_TOKEN }} -var ROOT_PASS=${{ secrets.ENV_VAR_ROOT_PASS }} -var main-api-version=${{ env.SERVICE_VERSION }} ${{ vars.ENV_JOB_PATH }}
  
