name: Deploy to Nomad cluster

on:
  push:
    # branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      service_version:
        description: 'Use version of service in format "{major}.{minor}.{patch}"'
        required: true
        type: string
        
env:
  INFRO_REPO: book-hub-umsp/bh-infrastructure
  INFRO_REPO_BRANCH: master


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - run: apt install jq
    - name: Extract version from git tag
      if: github.event_name == 'push'
      id: get-tag
      run: |
        tag=$(echo ${{  github.ref_name }} | cut -dv -f2)
        echo "::set-output name=tag::$tag"
    - name: Checkout Infro repo
      uses: actions/checkout@v4
      with:
        repository: '${{ env.INFRO_REPO }}'
        ref: ${{ env.INFRO_REPO_BRANCH }}
        token: '${{ secrets.WORKFLOW_TOKEN }}'
    - name: Setup `nomad`
      uses: hashicorp/setup-nomad@main
      id: setup
      with:
        version: ${{ vars.ENV_NOMAD_VERSION }}
    - run: echo "${{ steps.get-tag.outputs.tag && steps.get-tag.outputs.tag || github.event.inputs.service_version }}"
    - name: Update version meta
      env:
        NOMAD_ADDR: ${{ vars.ENV_NOMAD_ADDR }}
        SERVICE_VERSION: ${{ steps.get-tag.outputs.tag && steps.get-tag.outputs.tag || github.event.inputs.service_version }}
      run: |
        jq '.Items' <<< $(nomad var get -namespace=${{ vars.ENV_NOMAD_NAMESPACE }} -out=${{ vars.ENV_NOMAD_VARIABLE_VERSION_META }}) > version.meta.json
        cat version.meta.json
        jq '.MAIN_API_VERSION = "${{ env.SERVICE_VERSION }}"' <<< $(cat version.meta.json) > version.meta.json
        cat version.meta.json
        nomad var put -token=${{ secrets.ENV_NOMAD_TOKEN }} -namespace="${{ vars.ENV_NOMAD_NAMESPACE }}" @version.meta.json
    - name: Run job
      env:
        NOMAD_ADDR: ${{ vars.ENV_NOMAD_ADDR }}
      run: |
        nomad job run -token=${{ secrets.ENV_NOMAD_TOKEN }} ${{ vars.ENV_JOB_PATH }}
  
